[GLOBAL]
colors = true
pantsd = false
local_store_dir = ".cache/lmdb_store"
named_caches_dir = ".cache/named_caches"

[coverage-py]
global_report = true
report = [
    "xml",
]

[python]
interpreter_search_paths = ["/opt/hostedtoolcache"]

[python-native-code]
cpp_flags = ["-I/usr/local/include/python3.9/"]

[test]
use_coverage = true
