name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Perform CI Checks
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 3
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # v0 makes it easy to bust the cache if needed
        # just increase the integer to start with a fresh cache
        gha-cache-key: v0
        named-caches-hash: ${{ hashFiles('vendor/constrains.txt') }}
        cache-lmdb-store: 'true'
    - name: Bootstrap Pants
      run: |
        pants --version
    - name: Check BUILD files
      run: |
        pants tailor --check update-build-files --check ::
    - name: Lint and typecheck
      run: |
        pants lint check ::
    - name: Test
      run: |
        pants test ::
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: ./dist/coverage/python/coverage.xml
    - name: Upload pants log
      uses: actions/upload-artifact@v3
      with:
        name: pants-log
        path: .pants.d/pants.log
      if: always()  # We want the log even on failures.
