name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Perform CI Checks
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 3
    - name: Setup Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache0-py${{ matrix.python_version }}
        named-caches-hash: ${{ hashFiles('vendor/lock/*.txt') }}
    - name: Bootstrap Pants
      run: |
        ./pants --version
    - name: Check BUILD files
      run: |
        ./pants --changed-since=HEAD~2 tailor --check update-build-files --check
    - name: Lint
      run: |
        ./pants --changed-since=HEAD~2 lint ::
    - name: Typecheck
      run: |
        ./pants --changed-since=HEAD~2 --changed-dependees=transitive check ::
    - name: Test
      run: |
        ./pants --changed-since=HEAD~2 --changed-dependees=transitive test ::
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: ./dist/coverage/python/coverage.xml
    - name: Upload pants log
      uses: actions/upload-artifact@v3
      with:
        name: pants-log
        path: .pants.d/pants.log
      if: always()  # We want the log even on failures.
